### ISSUE TITLE
Allow line numbers to be passed on to error messages

### ISSUE THREAD

**Issue by uhaciogullari** [PureKrome/EcmaScript.NET#3]
YUICompressor.NET MSBuild task [can't show the line numbers for error messages](https://github.com/PureKrome/YUICompressor.NET/issues/7). @freeranger pointed out this is related to EcmaScript.NET.

Anyway we can fix it? I checked the source code, couldn't find any unit tests for this library. The ones in YUICompressor.NET pass.

**Comment by 501st-alpha1** [comment]
This would be useful for me too. Currently, when I see an error I have to resort to a manual [binary search](https://en.wikipedia.org/wiki/Binary_search_algorithm) of the file, which is less than ideal.

**Comment by PureKrome** [comment]
Closing this issue as this repo is now Archived.
