### ISSUE TITLE
"missing name after . operator" issue

### ISSUE THREAD

**Issue by slgal** [PureKrome/EcmaScript.NET#4]
Hello, I am using YUI compressor and I found that it's throw an errors with one of my custom file.
I did some debug and  found that the problem inside EcmaScript.NET.
Next code will throw an error:

> An unhandled exception of type 'EcmaScript.NET.EcmaScriptRuntimeException' occurred in ConsoleApplication1.exe
> Additional information: missing name after . operator

```
static void Main(string[] args)
       {
            var js = @"alert(web.import);";
           using (var memoryStream = new MemoryStream(Encoding.UTF8.GetBytes(js)))
            {
                var stream = new StreamReader(memoryStream, Encoding.UTF8);
                 var compilerEnvirons = new CompilerEnvirons();
                var parser = new Parser(compilerEnvirons, new CustomErrorReporter());
                parser.Parse(stream, null, 1);
            }
        }
```

While `var js = @"alert(web.import1);";` works fine. 

Attach some other examples:

```
var js = @"signup.package = function () { }";
var js = @"resources.web.import.validation = function () { };";
```

EDIT: Fixed formatting by @PureKrome

**Comment by slgal** [comment]
Looks like import and package is js keywords. Is it possible to fix it?

**Comment by PureKrome** [comment]
hi @slgal - thanks for the issue.

I've had a quick play (read an hour or so) with the code and I could get `import` working (working == exception not thrown .. but not tested if it's still valid js, etc) but not `package`. I also had a quick look at the YUICompressor ([original java version](https://github.com/yui/yuicompressor/blob/master/src/org/mozilla/javascript/Parser.java)) and noticed that what i was playing around with ends up being a bit different to theirs.

also, their latest file(s) are waaaay newer than this repo's.

So these are my thoughts :

- Find an online version of the latest java YUICompressor and test your error-text against the latest version.
- Files in here need to be updated to latest java's repo code (assuming it works against current java code).

As such, I don't have the time to do this --- so I can't fix it. Happy to accept PR's but that's about it :(

I know that's not the answer you were hoping, so I'm sorry.

**Comment by slgal** [comment]
Hi @PureKrome, thank you for your answer. I downloaded the latest YUICompressor (v2.4.8) jar file and tried to compress file with same code. I get same results.
See more here: https://github.com/yui/yuicompressor/issues/250

**Comment by PureKrome** [comment]
@slgal - great !! I've subscribed to that thread to see if anything _might_ help. I've got a scary feeling that the entire code base (here) is waaay out of date so a huge effort will be needed to catch up to the latest java version.

**Comment by PureKrome** [comment]
Out of interest folks, what version of .NET framework are you guys using in your project, which is using this package?

**Comment by mdvorscak** [comment]
We're on 4.6.2

**Comment by PureKrome** [comment]
New `pre-release` is available on NuGet. please see if that fixes this issue.

More info in #8 about this.

**Comment by alexazarh** [comment]
I had the same problem like @mdvorscak and upgrading to the new pre-release solved it.

**Comment by PureKrome** [comment]
Oh nice! great to hear someone tested it :) Kewl. i'll give it a few more days before I make it an official release. Would love to hear if others can give it a go.
