### ISSUE TITLE
// Comments not getting converted to /* */ 

### ISSUE THREAD

**Issue by hexxone** [PureKrome/EcmaScript.NET#5]
I've just minimized one of my old projects just for fun, and when trying to run it I noticed that it was broken.. The syntax got completely destroyed since I had a lot of double-slash ( // ) comments which end with the line and therefore need to be converted to /\* */ comments ot have a newline eachafter for the script to stay intact :smile:

**Comment by PureKrome** [comment]
Closing this issue as this repo is now Archived.
